[lcms]
language = "c"
compile_commands_path = "database/lcms/latest/build_asan/compile_commands.json"
document_paths = [
    "database/lcms/latest/code/README.md",
    "database/lcms/latest/code/doc",
]
document_has_api_usage = true
output_path = "database/lcms/latest/out"
header_paths = ["database/lcms/latest/code/include"]
driver_build_args = ["database/lcms/latest/bin_asan/lib/liblcms2.a"]
consumer_case_paths = [
    "database/lcms/latest/code/fuzzers",
    "database/lcms/latest/code/testbed",
]
